# 映射端口
server:
  port: 8099
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/cys
    password: chen321
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.cys.pojo